# Generated by Django 3.0.5 on 2020-04-27 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='upload',
            field=models.ImageField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.CharField(max_length=240, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registrationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
