# Generated by Django 3.0.5 on 2020-04-27 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200427_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registrationDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
