# Generated by Django 3.0.5 on 2020-04-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200427_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registrationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
