# Generated by Django 3.0.5 on 2020-04-28 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200427_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registrationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
